name: Publish Docker image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

env:  
  USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        run: echo $PASSWORD | docker login -u $USERNAME --password-stdin
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./DockerTutorial/Assignment3/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-image:latest
